### ISSUE TITLE
ImportError: No module named 'numpy.core.multiarray\r'

### ISSUE THREAD

**Issue by wudongming97** [aleksispi/drl-rpn-tf#2]
Hello! I met some problems. Can you give me some suggestions? Thanks a lot!

``...
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /home/cgv841/wudongming/drl-rpn-tf/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
Loaded dataset `voc_2012_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "/home/cgv841/wudongming/drl-rpn-tf/tools/../lib/datasets/pascal_voc.py", line 111, in gt_roidb
    roidb = pickle.load(fid)
ImportError: No module named 'numpy.core.multiarray\r'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/trainval_net.py", line 117, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 89, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 89, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 86, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/cgv841/wudongming/drl-rpn-tf/tools/../lib/model/train_val.py", line 460, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/cgv841/wudongming/drl-rpn-tf/tools/../lib/datasets/imdb.py", line 114, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/cgv841/wudongming/drl-rpn-tf/tools/../lib/datasets/imdb.py", line 74, in roidb
    self._roidb = self.roidb_handler()
  File "/home/cgv841/wudongming/drl-rpn-tf/tools/../lib/datasets/pascal_voc.py", line 113, in gt_roidb
    roidb = pickle.load(fid, encoding='bytes')
ImportError: No module named 'numpy.core.multiarray\r'
Command exited with non-zero status 1
8.00user 0.71system 0:09.17elapsed 95%CPU (0avgtext+0avgdata 282404maxresident)k
0inputs+0outputs (0major+59566minor)pagefaults 0swaps

I run it on Ubuntu 16.04, python 3.5

In fact, in virtual env, I can import numpy.core.multiarray and the file independently.
And, 'voc_2007_trainval gt roidb loaded from /home/cgv841/wudongming/drl-rpn-tf/data/cache/voc_2007_trainval_gt_roidb.pkl' is printed.

**Comment by aleksispi** [comment]
Hi wudongming97. Sorry for the late response. I have not encountered such an issue before. Do you get the same issue if you try to install and run the tf-faster-rcnn code on top of which drl-RPN is implemented? I.e. if you try to follow and run the steps in https://github.com/endernewton/tf-faster-rcnn? Because looking at your error message, it appears not to be related to any of the core drl-RPN code, but rather some dataset pickle stuff -- hence I suspect that the issue is at the level of tf-faster-rcnn (or even deeper down). 

If you try that and it seems to work to use tf-faster-rcnn, then I'll investigate this more thoroughly as it has to do with the drl-RPN code somehow.

Btw, it should work on Ubuntu 16.04 with python 3.5.

Best,
Aleksis

**Comment by aleksispi** [comment]
Closing due to inactivity -- likely an issue of a parent repo as mentioned in my above comment.
